version: '3'
services:

  web:
    container_name: web
    image: hyerin9177/action-sample
    expose:
      - 8080
    ports:
      - 8080:8080

  nginx:
    container_name: nginx
    image: hyerin9177/action-sample-nginx
    depends_on:
      - web